# Generated by Django 5.2.7 on 2025-10-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('groomer_id', 'appointment_date', 'appointment_time')},
        ),
    ]
